AWSTemplateFormatVersion: "2010-09-09"
Description: s3 bucket - v1

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "my-cloudformation-s3-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true