version: '3.7'

networks:
  local-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16


services:
  zookeeper: # the configuration manager
    hostname: zookeeper
    container_name: zookeeper
    image: zookeeper:3.7.0
    ports:
      - 2888:2888
      - 2181:2181
      - 3888:3888
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - local-network

  nifi:
    image: apache/nifi:1.12.1
    container_name: nifi
    ports:
      - 8090:8090
    environment:
      - NIFI_WEB_HTTP_PORT=8090
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    networks:
      - local-network
