version: '3.7'

networks:
  local-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16

# https://hub.docker.com/_/neo4j?tab=description
services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.4.7-community
    restart: unless-stopped
    ports:
      - 7473:7473
      - 7474:7474
      - 7687:7687
    environment:
# user / password
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    networks:
      - local-network
