version: '3.7'

networks:
  local-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16

services:
  metabase:
    container_name: metabase
    image: metabase/metabase
    ports:
     - "3000:3000"
    networks:
      - local-network